typography_spectrum: 0.49830123921856284
color:
  brandStrength: 0.21383925108239055
  lightness: 0.6122438758611679
  saturation: 0.8118840563111007
  rhythmicContrast: 0.26367801311425865
  brandColors:
    - '#7D8A2E'
    - '#C9D787'
    - '#FFFFFF'
    - '#FFC0A9'
    - '#FF8598'
layout_spectrum: 0.09753089724108577
name: culture catharsis
navigation:
  - name: Blog
    url: 'http://culturecatharsis.com'
    type: external
  - name: Twitter
    url: 'https://twitter.com/diftol'
    type: external
  - name: LinkedIn
    url: 'https://uk.linkedin.com/in/daniel-hultgren-05079b3a'
    type: external
  - name: Facebook
    url: 'https://www.facebook.com/diftol'
    type: external
title: Daniel Hultgren
description: An online calling card
